[package]
name = "alpha-tak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tak = {path = "../tak"}
rand = "0.8"
tch = { git = "https://github.com/ViliamVadocz/tch-rs", branch = "shuffle-device" }
lazy_static = "1.4"